# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
mantle = "blake-mealey/mantle@0.11.2"
remodel = "rojo-rbx/remodel@0.10.0"
rojo = "rojo-rbx/rojo@7.2.0"
tarmac = "Roblox/tarmac@0.7.0"