[package]
name = "sentinel/rts"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
FastCastRedux = "encodedvenom/fastcastredux@0.1.3"
Input = "sleitnick/input@2.1.0"
Janitor = "howmanysmall/janitor@1.14.1"
Matter = "evaera/matter@0.6.1"
Plasma = "evaera/plasma@0.4.2"
Promise = "evaera/promise@4.0.0"
Rewire = "sayhisam1/rewire@0.3.0"
Silo = "sleitnick/silo@0.1.0"
TestEZ = "roblox/testez@0.4.1"